# Generated by Django 3.0.8 on 2020-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_confirmemailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='filename',
            field=models.FileField(default='2020-10-15', upload_to='data/price', verbose_name='Актуальный прайс-лист'),
            preserve_default=False,
        ),
    ]
