# Generated by Django 3.0.8 on 2020-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.FileField(upload_to='data/price/', verbose_name='Актуальный прайс-лист'),
        ),
    ]
