# Generated by Django 3.0.8 on 2020-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201016_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=1000, verbose_name='Внешний ИД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='Модель'),
        ),
    ]
