# Generated by Django 3.0.8 on 2020-10-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201019_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='street',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='building',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='house',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='structure',
        ),
    ]
