# Generated by Django 3.1.1 on 2021-01-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201019_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='filename',
            new_name='filename1',
        ),
    ]
